
**======================================================================================================**
<p align="center"><b>|| FUSION 1 || PROYECTO ANÁLISIS DE DATOS</b></p>

**======================================================================================================**
**Integrantes:**  
*   Vismark Abner Choque Cachi
*   Elizabeth Cusi Ancasi
  
**Materia: Analisis de Datos**  
**Docente: M.Sc. Madelina Loza Soliz**  
**Sigla: DAT-263**
**======================================================================================================**

## **IMPORTACION DE LOS DATASETS**

In [1]:
import pandas as pd
datos_estudiantes = pd.read_csv("data/analisis/prepro_datos_estudiantes.csv") # este es el tuyo
data_notas = pd.read_csv("data/analisis/notas_ancho.csv")

In [2]:
datos_estudiantes.head()

,dip,Género,Provincia,Ciudad,Colegio,Administración del Colegio,Edad
0,260910,MASCULINO,MURILLO,LA PAZ,SAN CALIXTO,FISCAL,16
1,487541,MASCULINO,MURILLO,LA PAZ,COL.NAL.TEC.HUM. FRANZ TAMAYO NAAAAAAAAO3,FISCAL,31
2,748784,MASCULINO,MURILLO,LA PAZ,DIVINO MAESTRO,PRIVADA,33
3,1763419,MASCULINO,MURILLO,LA PAZ,CIE 12 DE OCTUBRE,FISCAL,51
4,2140504,MASCULINO,MURILLO,LA PAZ,SAN CALIXTO,FISCAL,16

In [3]:
data_notas.head()

,Carrera,Gestión,Periodo,C.I.,Nota2T,NotaBIO-99,NotaCOM-99,NotaEST-99,NotaFIS-99,NotaGMT-99,NotaINF-99,NotaLIN-99,NotaMAT-99,NotaPSA,NotaQMC-99,promedio_aprobacion,Estado,nivel de aprendizaje
0,Biologia,2009,SEGUNDO,4295732,-1.0,60.0,-1.0,-1.0,67.0,-1.0,-1.0,-1.0,52.0,-1.0,66.0,61.25,1,4
1,Biologia,2009,SEGUNDO,4299485,-1.0,52.0,-1.0,-1.0,51.0,-1.0,-1.0,-1.0,39.0,-1.0,27.0,42.25,0,3
2,Biologia,2009,SEGUNDO,4751856,-1.0,73.0,-1.0,-1.0,55.0,-1.0,-1.0,-1.0,51.0,-1.0,73.0,63.00,1,4
3,Biologia,2009,SEGUNDO,4755839,-1.0,0.0,-1.0,-1.0,0.0,-1.0,-1.0,-1.0,0.0,-1.0,0.0,0.00,0,1
4,Biologia,2009,SEGUNDO,4766488,-1.0,18.0,-1.0,-1.0,0.0,-1.0,-1.0,-1.0,8.0,-1.0,6.0,8.00,0,1

In [4]:
data_notas.shape

(5691, 18)

## **CORTA DESCRIPCION DEL DATASET**

### **Dataset "DATOS ESTUDIANTES MADE"**

In [5]:

datos_estudiantes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1987 entries, 0 to 1986
Data columns (total 7 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   dip                         1987 non-null   int64
 1   Género                      1987 non-null   object
 2   Provincia                   1987 non-null   object
 3   Ciudad                      1987 non-null   object
 4   Colegio                     1987 non-null   object
 5   Administración del Colegio  1987 non-null   object
 6   Edad                        1987 non-null   int64
dtypes: int64(2), object(5)
memory usage: 108.8+ KB

### **Dataset "NOTAS MADE"**

In [6]:
data_notas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5691 entries, 0 to 5690
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Carrera               5691 non-null   object
 1   Gestión               5691 non-null   int64
 2   Periodo               5691 non-null   object
 3   C.I.                  5691 non-null   object
 4   Nota2T                5691 non-null   float64
 5   NotaBIO-99            5691 non-null   float64
 6   NotaCOM-99            5691 non-null   float64
 7   NotaEST-99            5691 non-null   float64
 8   NotaFIS-99            5691 non-null   float64
 9   NotaGMT-99            5691 non-null   float64
 10  NotaINF-99            5691 non-null   float64
 11  NotaLIN-99            5691 non-null   float64
 12  NotaMAT-99            5691 non-null   float64
 13  NotaPSA               5691 non-null   float64
 14  NotaQMC-99            5691 non-null   float64
 15  promedio_aprobacion   5691 non-null   float64
 16  Estado                5691 non-null   int64
 17  nivel de aprendizaje  5691 non-null   int64
dtypes: float64(12), int64(3), object(3)
memory usage: 800.4+ KB

**CONVERSION DE DATOS**  
Antes de nada empezar con la fusion de los datasets se hace la conversion de las columnas identificadoras de ambos datasets en un mismo tipo, asi no tener problemas en la fusion

In [7]:
data_notas["C.I."] = data_notas["C.I."].astype(str).str.strip()
datos_estudiantes["dip"] = datos_estudiantes["dip"].astype(str).str.strip()

# **FUSION DE DATASETS**

El siguiente código realiza una **fusión interna** (`INNER JOIN`) entre los dos DataFrames (`datos_estudiantes` y `data_notas`) utilizando los identificadores únicos validados previamente.
## **Componentes de la Fusión**

| Componente | Rol en el DataFrame | Descripción |
| :--- | :--- | :--- |
| **`datos_estudiantes`** | **Izquierda** | Contiene la información demográfica, ubicación y el identificador **`dip`**. |
| **`data_notas`** | **Derecha** | Contiene las notas del examen y el identificador **`C.I.`**. |
| **`left_on="dip"`** | **Clave Izquierda** | La columna **`dip`** de la tabla izquierda se usará para la coincidencia. |
| **`right_on="C.I."`** | **Clave Derecha** | La columna **`C.I.`** de la tabla derecha se usará para la coincidencia. |
| **`how="inner"`** | **Tipo de Unión** | **Fusión Interna (`INNER JOIN`)**. Solo se incluyen las filas donde **`dip` es idéntico a `C.I.`**. |

In [8]:
# Conjuntos únicos
set_notas = set(data_notas["C.I."])
set_dips  = set(datos_estudiantes["dip"])

# Intersección
coinciden_unicos = set_notas & set_dips

print("Cantidad de identificadores únicos que coinciden:", len(coinciden_unicos))

Cantidad de identificadores únicos que coinciden: 351

Se tiene 342 identificadores unicos "C.I."

In [9]:
fusion = datos_estudiantes.merge(
    data_notas,
    left_on="dip",
    right_on="C.I.",
    how="inner"
)
print("------------------------------------------------")
print("Total de filas fusionadas:", len(fusion))

print("------------------------------------------------")
print(fusion.info())

------------------------------------------------
Total de filas fusionadas: 421
------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421 entries, 0 to 420
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   dip                         421 non-null    object
 1   Género                      421 non-null    object
 2   Provincia                   421 non-null    object
 3   Ciudad                      421 non-null    object
 4   Colegio                     421 non-null    object
 5   Administración del Colegio  421 non-null    object
 6   Edad                        421 non-null    int64
 7   Carrera                     421 non-null    object
 8   Gestión                     421 non-null    int64
 9   Periodo                     421 non-null    object
 10  C.I.                        421 non-null    object
 11  Nota2T                      421 non-null    float64
 12  NotaBIO-99                  421 non-null    float64
 13  NotaCOM-99                  421 non-null    float64
 14  NotaEST-99                  421 non-null    float64
 15  NotaFIS-99                  421 non-null    float64
 16  NotaGMT-99                  421 non-null    float64
 17  NotaINF-99                  421 non-null    float64
 18  NotaLIN-99                  421 non-null    float64
 19  NotaMAT-99                  421 non-null    float64
 20  NotaPSA                     421 non-null    float64
 21  NotaQMC-99                  421 non-null    float64
 22  promedio_aprobacion         421 non-null    float64
 23  Estado                      421 non-null    int64
 24  nivel de aprendizaje        421 non-null    int64
dtypes: float64(12), int64(4), object(9)
memory usage: 82.4+ KB
None

Visualizacion de datos

In [10]:
fusion.head(20)

,dip,Género,Provincia,Ciudad,Colegio,Administración del Colegio,Edad,Carrera,Gestión,Periodo,...,NotaFIS-99,NotaGMT-99,NotaINF-99,NotaLIN-99,NotaMAT-99,NotaPSA,NotaQMC-99,promedio_aprobacion,Estado,nivel de aprendizaje
0,260910,MASCULINO,MURILLO,LA PAZ,SAN CALIXTO,FISCAL,16,Biologia,2012,PRIMERO,...,0.0,-1.0,-1.0,-1.0,0.0,-1.0,10.0,2.500000,0,1
1,260910,MASCULINO,MURILLO,LA PAZ,SAN CALIXTO,FISCAL,16,Biologia,2013,PRIMERO,...,0.0,-1.0,-1.0,-1.0,0.0,-1.0,0.0,0.000000,0,1
2,2318517,MASCULINO,MURILLO,LA PAZ,LIBERTADORES DE AMERICA,FISCAL,52,Biologia,2012,PRIMERO,...,17.0,-1.0,-1.0,-1.0,0.0,-1.0,21.0,18.000000,0,1
3,2379805,NO RESPONDE,MURILLO,LA PAZ,SAN CALIXTO,FISCAL,52,Física,2010,PRIMERO,...,26.0,-1.0,-1.0,-1.0,10.0,-1.0,51.0,34.500000,0,2
4,2539628,MASCULINO,MURILLO,LA PAZ,AMERICAN SCHOOL,PRIVADA,51,Física,2013,SEGUNDO,...,9.0,-1.0,-1.0,-1.0,17.0,-1.0,15.0,13.500000,0,1
5,2539628,MASCULINO,MURILLO,LA PAZ,AMERICAN SCHOOL,PRIVADA,51,Física,2015,PRIMERO,...,4.0,-1.0,-1.0,-1.0,0.0,-1.0,20.0,9.250000,0,1
6,2643974,FEMENINO,MURILLO,LA PAZ,LOS PINOS,PRIVADA,44,Física,2009,SEGUNDO,...,11.0,-1.0,26.0,-1.0,15.0,-1.0,29.0,20.250000,0,2
7,3324122,FEMENINO,MURILLO,LA PAZ,TEC. MIXTO FABRIL 18 DE MAYO FE Y ALEGRIA,FISCAL,45,Ciencias Químicas,2010,SEGUNDO,...,0.0,-1.0,-1.0,-1.0,0.0,-1.0,4.0,1.500000,0,1
8,3489994,MASCULINO,MURILLO,LA PAZ,INSTITUTO DOMINGO SAVIO,PRIVADA,35,Estadística,2011,PRIMERO,...,63.0,-1.0,68.0,-1.0,87.0,-1.0,-1.0,72.666667,1,4
9,3999799,MASCULINO,SUD CHICHAS,TUPIZA,COLEGIO ACIONAL MIXTO SUIPACHA,FISCAL,35,Ciencias Químicas,2010,PRIMERO,...,89.0,-1.0,-1.0,-1.0,9.0,-1.0,52.0,50.500000,0,3
10,4013771,MASCULINO,SUD CHICAS,TUPIZA,NACIONAL MIXTO SUIPACHA,FISCAL,46,Biologia,2015,PRIMERO,...,0.0,-1.0,-1.0,-1.0,0.0,-1.0,8.0,2.000000,0,1
11,4041686,MASCULINO,QUIJARRO,KILPANI,MONS SEAAOR RICARDO BENI MORO,FISCAL,44,Informática,2009,SEGUNDO,...,0.0,-1.0,0.0,-1.0,1.0,-1.0,-1.0,0.250000,0,1
12,4110555,FEMENINO,OROPEZA,CHUQUISACA,LA SALLE,PRIVADA,32,Biologia,2012,PRIMERO,...,0.0,-1.0,-1.0,-1.0,0.0,-1.0,0.0,0.000000,0,1
13,4114928,FEMENINO,MURILLO,LA PAZ,SAN CALIXTO,PRIVADA,30,Biologia,2012,SEGUNDO,...,21.0,-1.0,-1.0,-1.0,11.0,-1.0,27.0,25.750000,0,2
14,4114928,FEMENINO,MURILLO,LA PAZ,SAN CALIXTO,PRIVADA,30,Biologia,2013,PRIMERO,...,51.0,-1.0,-1.0,-1.0,18.0,-1.0,51.0,40.750000,0,3
15,4278207,MASCULINO,MURILLO,LA PAZ,BOLIVIANO NORUEGO,PRIVADA,41,Informática,2009,SEGUNDO,...,43.0,-1.0,38.0,-1.0,26.0,-1.0,-1.0,41.250000,0,3
16,4279717,MASCULINO,MURILLO,LA PAZ,INSTITUTO AMERICANO,PRIVADA,36,Física,2011,SEGUNDO,...,71.0,-1.0,78.0,-1.0,55.0,-1.0,66.0,67.500000,1,4
17,4295732,FEMENINO,MURILLO,LA PAZ,CRISTO REY,PRIVADA,34,Biologia,2009,SEGUNDO,...,67.0,-1.0,-1.0,-1.0,52.0,-1.0,66.0,61.250000,1,4
18,4299485,FEMENINO,MURILLO,LA PAZ,BOLIVIANO JAPONES,PRIVADA,34,Biologia,2009,SEGUNDO,...,51.0,-1.0,-1.0,-1.0,39.0,-1.0,27.0,42.250000,0,3
19,4299485,FEMENINO,MURILLO,LA PAZ,BOLIVIANO JAPONES,PRIVADA,34,Biologia,2010,PRIMERO,...,57.0,-1.0,-1.0,-1.0,33.0,-1.0,26.0,40.000000,0,2

# **ANALISIS DE DATOS**


En este análisis se trabaja con el DataFrame `fusion`, donde se calculó la **edad de los postulantes** restando su año de nacimiento al año 2025:

## **1. Distribución general de edades**
Se genera un **histograma** de la variable `Edad`:

- Permite observar **qué rangos de edad son más comunes** entre los postulantes.
- Identifica posibles **valores extremos** o dispersión en la población.

In [11]:
!pip install plotly -q

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [12]:
import plotly.express as px
import pandas as pd

# Verificar columnas
print("Columnas disponibles:", fusion.columns.tolist())

# Confirmar que exista la columna Edad
if "Edad" not in fusion.columns:
    raise ValueError(" ERROR: La columna 'Edad' no existe en el DataFrame fusion.")

# Histograma
fig = px.histogram(
    fusion,
    x="Edad",
    nbins=30,
    title="Distribución de Edad de los Postulantes",
    color_discrete_sequence=["#88C0D0"]
)

fig.update_layout(
    xaxis_title="Edad",
    yaxis_title="Cantidad de Postulantes",
    title_font_size=22,
    template="simple_white"
)

fig.show()

Columnas disponibles: ['dip', 'Género', 'Provincia', 'Ciudad', 'Colegio', 'Administración del Colegio', 'Edad', 'Carrera', 'Gestión', 'Periodo', 'C.I.', 'Nota2T', 'NotaBIO-99', 'NotaCOM-99', 'NotaEST-99', 'NotaFIS-99', 'NotaGMT-99', 'NotaINF-99', 'NotaLIN-99', 'NotaMAT-99', 'NotaPSA', 'NotaQMC-99', 'promedio_aprobacion', 'Estado', 'nivel de aprendizaje']

Con base en los resultados obtenidos, se observa que la mayoría de los postulantes tiene entre 30 y 40 años. Esto indica que se trata, en gran parte, de personas adultas que probablemente ya cuentan con una carrera previa o experiencia profesional, y que ahora están buscando ampliar su formación. Esto resulta coherente si consideramos que la Facultad de Ciencias Puras y Naturales tiene las carreras de: Informática, Matemática, Física, Química, Estadística y Biología, carreras que atraen a quienes desean actualizarse, especializarse o reorientar su trayectoria profesional hacia disciplinas científicas.

## **2. Comparación de edades por Género**
Se utiliza un **boxplot** que compara la edad según el género:

- Visualiza **mediana, cuartiles y valores atípicos** por género.
- Detecta si existen diferencias significativas entre hombres y mujeres.

In [13]:

# Boxplot por género
fig = px.box(
    fusion, x="Género", y="Edad",
    title="Edad por Género",
    color="Género",
    color_discrete_sequence=px.colors.qualitative.Pastel
)
fig.show()

## **3. Comparación de edades por tipo de administración del colegio**
Se construye otro **boxplot** que compara la edad según el tipo de administración del colegio (público, privado, subvencionado, etc.):

- Permite identificar **patrones de edad asociados al tipo de colegio**.
- Detecta diferencias en la edad promedio o la dispersión entre los distintos tipos de colegios.

In [14]:
import plotly.express as px

# Crear el boxplot
fig = px.box(
    fusion, x="Administración del Colegio", y="Edad",
    title="Edad por Tipo de Administración del Colegio",
    color="Administración del Colegio",
    color_discrete_sequence=px.colors.qualitative.Pastel
)

# Calcular frecuencias por categoría
frecuencias = fusion["Administración del Colegio"].value_counts()

# Agregar anotaciones sobre cada caja
for i, categoria in enumerate(frecuencias.index):
    fig.add_annotation(
        x=categoria,
        y=fusion["Edad"].max() + 2,  # posición un poco arriba del max
        text=f"n={frecuencias[categoria]}",
        showarrow=False,
        font=dict(size=12, color="black")
    )

fig.show()

In [15]:
# Contar la cantidad de casos por categoría
frecuencias = fusion["Administración del Colegio"].value_counts()
print(frecuencias)

Administración del Colegio
FISCAL      206
PRIVADA     181
CONVENIO     24
CEMA         10
Name: count, dtype: int64


## **4. Desempeño de los postulantes por carrera**
 **1. Filtros interactivos**
Se incorporan **widgets interactivos** que permiten al usuario seleccionar:

- Una o varias **ciudades** de procedencia.
- Uno o varios **géneros**.

 **2. Cálculo de indicadores**
Para cada carrera, se calculan:

- **Total de postulantes**
- **Cantidad de aprobados** (Estado = 1)
- **Cantidad de reprobados** (Estado = 0)
- **Porcentaje de aprobación** (% Aprobación)


**Esto permite:**
- Permite comparar rápidamente **el rendimiento de los postulantes entre carreras**.
- Identifica **carreras con mayor o menor tasa de aprobación**.
- Facilita el análisis por **ciudad y género** gracias a los filtros interactivos.

In [16]:
!pip install ipywidgets -q

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [17]:
import ipywidgets as widgets
from IPython.display import display, clear_output

# --- UNA SOLA VEZ: pre-calculamos todo y copiamos solo lo necesario ---
df = fusion[["C.I.", "Carrera", "Estado", "Ciudad", "Género"]].copy()
df["Género"] = df["Género"].astype("category")
df["Ciudad"] = df["Ciudad"].astype("category")
df["Carrera"] = df["Carrera"].astype("category")
df["Estado"] = df["Estado"].astype("int8")  # 0 o 1

# Pre-calculamos el resumen completo una sola vez
resumen_total = (
    df.groupby(["Carrera", "Ciudad", "Género", "Estado"], observed=True)["C.I."]
    .count()
    .reset_index(name="Cantidad")
    .astype({"Cantidad": "int32"})
)

# Opciones disponibles
ciudades = list(df["Ciudad"].cat.categories)
generos = list(df["Género"].cat.categories)

# Creamos listas de checkboxes para cada filtro
ciudad_checkboxes = []
for ciudad in ciudades:
    cb = widgets.Checkbox(
        value=True,
        description=str(ciudad),
        indent=False,
        layout=widgets.Layout(width="220px")
    )
    cb._valor = ciudad  # guardamos el valor real de la categoría
    ciudad_checkboxes.append(cb)

genero_checkboxes = []
for genero in generos:
    cb = widgets.Checkbox(
        value=True,
        description=str(genero),
        indent=False,
        layout=widgets.Layout(width="160px")
    )
    cb._valor = genero
    genero_checkboxes.append(cb)

# Contenedores visuales estilo "tarjeta"
ciudad_box = widgets.VBox([
    widgets.HTML("<b>Ciudad</b>"),
    widgets.GridBox(
        ciudad_checkboxes,
        layout=widgets.Layout(
            grid_template_columns="repeat(2, 230px)",
            grid_gap="4px 12px"
        )
    )
])

genero_box = widgets.VBox([
    widgets.HTML("<b>Género</b>"),
    widgets.VBox(genero_checkboxes)
])

filtros_contenido = widgets.HBox(
    [ciudad_box, genero_box],
    layout=widgets.Layout(justify_content="space-around", padding="10px 20px")
)

filtros_card = widgets.VBox(
    [
        widgets.HTML("""
        <div style='font-size:16px; font-weight:bold; margin-bottom:4px;'>
            Filtros de Postulantes
        </div>
        <div style='font-size:12px; color:#555;'>
            Marca o desmarca opciones para actualizar el gráfico en tiempo real.
        </div>
        """),
        filtros_contenido
    ],
    layout=widgets.Layout(
        border="1px solid #ccc",
        padding="10px 15px",
        margin="5px 0 10px 0",
        border_radius="8px",
        width="100%"
    )
)

# Acordeón plegable para no ocupar tanto espacio en la vista
filtros_accordion = widgets.Accordion(children=[filtros_card])
filtros_accordion.set_title(0, "Filtros de Postulantes")
# Inicia cerrado (None). Si quieres que inicie abierto, cambia a 0
filtros_accordion.selected_index = None

salida_mejorada = widgets.Output()


def _valores_seleccionados(checks):
    """Devuelve la lista de valores (_valor) seleccionados en un grupo de checkboxes."""
    return [cb._valor for cb in checks if cb.value]


def actualizar_rapido_mejorado(_=None):
    with salida_mejorada:
        clear_output(wait=True)

        ciudades_sel = _valores_seleccionados(ciudad_checkboxes)
        generos_sel = _valores_seleccionados(genero_checkboxes)

        if not ciudades_sel or not generos_sel:
            print("Selecciona al menos una ciudad y un género para ver el gráfico.")
            return

        # Filtro ultra-rápido sobre el resumen ya pre-agrupado
        mask = (
            resumen_total["Ciudad"].isin(ciudades_sel)
            & resumen_total["Género"].isin(generos_sel)
        )
        temp = resumen_total[mask]

        if temp.empty:
            print("No hay datos con los filtros seleccionados")
            return

        # Total por carrera con los filtros actuales
        total_por_carrera = temp.groupby("Carrera", observed=True)["Cantidad"].sum()

        # Pivot para tener Aprobados y Reprobados
        pivot = (
            temp.pivot_table(
                index="Carrera",
                columns="Estado",
                values="Cantidad",
                aggfunc="sum",
                fill_value=0,
                observed=False,
            )
            .rename(columns={0: "Reprobados", 1: "Aprobados"})
        )

        for col in ["Aprobados", "Reprobados"]:
            if col not in pivot.columns:
                pivot[col] = 0

        pivot = pivot[["Aprobados", "Reprobados"]].astype(int)
        pivot["Total"] = total_por_carrera
        pivot["Pct_Aprobados"] = (pivot["Aprobados"] / pivot["Total"] * 100).round(1)
        pivot["Pct_Reprobados"] = (pivot["Reprobados"] / pivot["Total"] * 100).round(1)

        # Formato largo para Plotly
        plot_df = pivot.reset_index().melt(
            id_vars="Carrera",
            value_vars=["Aprobados", "Reprobados"],
            var_name="Estado",
            value_name="Cantidad",
            
        )
        plot_df["Porcentaje"] = plot_df.apply(
            lambda row: pivot.loc[row["Carrera"], f"Pct_{row['Estado']}"], axis=1
        )

        fig = px.bar(
            plot_df,
            x="Carrera",
            y="Cantidad",
            color="Estado",
            text=plot_df["Porcentaje"].round(1).astype(str) + "%",
            title="Desempeño de Postulantes por Carrera (filtros aplicados)",
            barmode="stack",
            color_discrete_map={"Aprobados": "#69D3BE", "Reprobados": "#ED695D"},
            hover_data={"Total": pivot["Total"].reindex(plot_df["Carrera"]).values},
        )

        fig.update_traces(textposition="inside")
        fig.update_layout(
            height=650,
            width=1100,
            plot_bgcolor="rgba(245,245,245,1)",
            margin=dict(t=60, l=40, r=20, b=40),
        )
        fig.show()


# Conectamos los cambios de cualquier checkbox a la actualización del gráfico
def _on_checkbox_change(change):
    if change["name"] == "value":
        actualizar_rapido_mejorado()

for cb in ciudad_checkboxes + genero_checkboxes:
    cb.observe(_on_checkbox_change, names="value")

# Mostramos el panel completo (con filtros plegables)
ui_mejorado = widgets.VBox([
    filtros_accordion,
    salida_mejorada,
])

display(ui_mejorado)

# Primera ejecución
actualizar_rapido_mejorado()

VBox(children=(Accordion(children=(VBox(children=(HTML(value="\n        <div style='font-size:16px; font-weigh…

In [18]:
ranking = (
    fusion.groupby("Carrera")["Estado"]
    .mean()
    .mul(100)
    .sort_values(ascending=False)
    .reset_index()
    .head(10)
)

fig = px.bar(
    ranking, x="Estado", y="Carrera",
    orientation="h",
    title="Top Carreras con Mayor Aprobación",
    color="Carrera"
)
fig.show()

## **5. Desempeño de Postulantes por Administración del Colegio**
SE OBSERVA a continuación cómo se distribuyen los **postulantes** y su **desempeño académico** (aprobados y reprobados) según el tipo de **administración del colegio**, considerando filtros por **carrera**, **género** y **tipo de administración**.

 **Filtros interactivos**
Se incorporan **widgets interactivos** que permiten al usuario seleccionar:

- Una o varias **carreras**.
- Uno o varios **géneros**.
- Una o varias **administraciones de colegio** (público, privado, etc.).

Esto permite explorar los datos de manera dinámica y ver cómo varía el desempeño según diferentes combinaciones.

**Cálculo de indicadores**
Para cada tipo de administración del colegio se calculan:

- **Total de postulantes**
- **Cantidad de aprobados**
- **Cantidad de reprobados**
- **Porcentaje de aprobación** (% Aprobación)

Estos indicadores permiten entender rápidamente la proporción de éxito de los postulantes en cada administración.

**Esto permite:**

- Comparar el **desempeño de los postulantes entre distintos tipos de administración**.
- Identificar qué administración tiene **mayor o menor porcentaje de aprobación**.
- Analizar cómo influyen la **carrera** y el **género** gracias a los filtros interactivos.

In [19]:
import pandas as pd
import plotly.express as px
import ipywidgets as widgets
from IPython.display import display, clear_output

# --- Copiar DataFrame ---
df = fusion.copy()
df["Género"] = df["Género"].astype(str)
df["Carrera"] = df["Carrera"].astype(str)
df["Administración del Colegio"] = df["Administración del Colegio"].astype(str)

# ======================================================
#     GENERACIÓN DE CHECKBOXES POR CATEGORÍA
# ======================================================

def generar_checkbox_group(titulo, valores, width="220px"):
    checks = []
    for v in sorted(valores):
        cb = widgets.Checkbox(
            value=True,
            description=str(v),
            indent=False,
            layout=widgets.Layout(width=width)
        )
        cb._valor = v
        checks.append(cb)

    caja = widgets.VBox([
        widgets.HTML(f"<b>{titulo}</b>"),
        widgets.VBox(checks)
    ])
    return checks, caja


# Crear checkboxes por categoría
checks_carrera, carrera_box = generar_checkbox_group(
    "Carrera", df["Carrera"].unique(), width="240px"
)

checks_genero, genero_box = generar_checkbox_group(
    "Género", df["Género"].unique(), width="160px"
)

checks_admin, admin_box = generar_checkbox_group(
    "Administración del Colegio", df["Administración del Colegio"].unique(), width="300px"
)

# Contenedor visual estilo tarjeta
filtros_card = widgets.VBox(
    [
        widgets.HTML("""
        <div style='font-size:16px; font-weight:bold; margin-bottom:4px;'>
            Filtros
        </div>
        <div style='font-size:12px; color:#555;'>
            Marca o desmarca opciones para actualizar el gráfico.
        </div>
        """),
        widgets.HBox([carrera_box, genero_box, admin_box],
                     layout=widgets.Layout(gap="30px", padding="10px"))
    ],
    layout=widgets.Layout(
        border="1px solid #ccc",
        border_radius="8px",
        padding="10px 15px",
        width="100%"
    )
)

# Acordeón para ocultar/mostrar filtros
filtros_accordion = widgets.Accordion(children=[filtros_card])
filtros_accordion.set_title(0, "Filtros")
filtros_accordion.selected_index = None  # inicia cerrado

# Contenedor de salida
salida = widgets.Output()


# ======================================================
#    FUNCIONES AUXILIARES
# ======================================================

def valores_seleccionados(checks):
    return [cb._valor for cb in checks if cb.value]


# ======================================================
#    FUNCIÓN DE ANÁLISIS (NO MODIFICADA)
# ======================================================
def analizar_admin_aprobacion(df, carreras, generos, administraciones):
    df_filtrado = df[
        df["Carrera"].isin(carreras) &
        df["Género"].isin(generos) &
        df["Administración del Colegio"].isin(administraciones)
    ]
    
    total = df_filtrado.groupby("Administración del Colegio")["C.I."].count().reset_index()
    total.columns = ["Administración del Colegio", "Total"]
    
    aprobados = df_filtrado[df_filtrado["Estado"] == 1].groupby("Administración del Colegio")["C.I."].count().reset_index()
    aprobados.columns = ["Administración del Colegio", "Aprobados"]
    
    reprobados = df_filtrado[df_filtrado["Estado"] == 0].groupby("Administración del Colegio")["C.I."].count().reset_index()
    reprobados.columns = ["Administración del Colegio", "Reprobados"]
    
    resumen = total.merge(aprobados, on="Administración del Colegio", how="left").merge(reprobados, on="Administración del Colegio", how="left")
    resumen[["Aprobados", "Reprobados"]] = resumen[["Aprobados", "Reprobados"]].fillna(0).astype(int)
    
    resumen["Pct_Aprobados"] = (resumen["Aprobados"] / resumen["Total"] * 100).round(1)
    resumen["Pct_Reprobados"] = (resumen["Reprobados"] / resumen["Total"] * 100).round(1)
    resumen[["Pct_Aprobados","Pct_Reprobados"]] = resumen[["Pct_Aprobados","Pct_Reprobados"]].fillna(0)

    resumen_long = resumen.melt(
        id_vars=["Administración del Colegio", "Total", "Pct_Aprobados", "Pct_Reprobados"],
        value_vars=["Aprobados", "Reprobados"],
        var_name="Estado",
        value_name="Cantidad"
    )

    resumen_long["Pct"] = resumen_long.apply(
        lambda r: r["Pct_Aprobados"] if r["Estado"] == "Aprobados" else r["Pct_Reprobados"],
        axis=1
    )

    resumen_long["Administración del Colegio"] = pd.Categorical(
        resumen_long["Administración del Colegio"],
        categories=sorted(df["Administración del Colegio"].unique()),
        ordered=True
    )

    return resumen_long


# ======================================================
#    FUNCIÓN PARA ACTUALIZAR GRÁFICO
# ======================================================
def actualizar(_=None):
    with salida:
        clear_output(wait=True)

        carreras = valores_seleccionados(checks_carrera)
        generos = valores_seleccionados(checks_genero)
        admins = valores_seleccionados(checks_admin)

        if not carreras or not generos or not admins:
            print("Selecciona al menos un valor en cada categoría.")
            return

        resumen_long = analizar_admin_aprobacion(df, carreras, generos, admins)

        if resumen_long.empty:
            print("No hay datos disponibles con esos filtros.")
            return

        fig = px.bar(
            resumen_long,
            x="Administración del Colegio",
            y="Cantidad",
            color="Estado",
            text="Pct",
            title="Desempeño de Postulantes por Administración del Colegio",
            barmode="stack",
            color_discrete_map={"Aprobados": "#4DECCC", "Reprobados": "#E66969"},
            hover_data=["Total", "Pct", "Estado"]
        )

        fig.update_traces(
            texttemplate="%{text:.1f}%",
            textposition="inside",
            hovertemplate=(
                "<b>%{x}</b><br>"
                "Estado: %{customdata[2]}<br>"
                "Cantidad: %{y}<br>"
                "Total: %{customdata[0]}<br>"
                "Porcentaje del estado: %{customdata[1]}%<extra></extra>"
            )
        )

        fig.update_layout(
            height=650,
            width=1100,
            plot_bgcolor="rgba(245,245,245,1)",
            title_x=0.5
        )
        fig.show()


# ======================================================
#    CONECTAR CHECKBOXES A ACTUALIZACIÓN
# ======================================================
for cb in checks_carrera + checks_genero + checks_admin:
    cb.observe(lambda change: actualizar(), names="value")


# ======================================================
#    MOSTRAR UI COMPLETA
# ======================================================
display(widgets.VBox([filtros_accordion, salida]))

# Primera ejecución
actualizar()

VBox(children=(Accordion(children=(VBox(children=(HTML(value="\n        <div style='font-size:16px; font-weigh…

## **6. Analisis de difultad por materia**
Este análisis muestra qué materias son más difíciles para los estudiantes según su carrera, gestión y género. Se calculan estadísticas como promedio, mediana, nota mínima y máxima, y porcentaje de reprobados. Los resultados se presentan mediante box plots y barras de promedio, permitiendo identificar de manera visual las materias con mayor dificultad y bajo rendimiento.

In [20]:
import pandas as pd
import plotly.express as px
import ipywidgets as widgets
from IPython.display import display, clear_output

# ================================================
# 1) Columnas de materias
# ================================================
columnas_materias = [c for c in fusion.columns if c.startswith("Nota")]

# ================================================
# 2) Función de análisis
# ================================================
def analizar_dificultad_por_carrera(df, carrera, gestion, genero):
    df_car = df[(df["Carrera"] == carrera) & (df["Gestión"] == gestion)].copy()

    if genero != "Todos":
        df_car = df_car[df_car["Género"] == genero]

    resultados = []

    for col in columnas_materias:

        notas_validas = df_car[col][df_car[col] != -1]

        if notas_validas.empty:
            continue

        materia = col.replace("Nota", "")
        total = len(notas_validas)
        aprob = (notas_validas >= 51).sum()
        reprob = (notas_validas < 51).sum()

        resultados.append({
            "Materia": materia,
            "Promedio": notas_validas.mean(),
            "Mediana": notas_validas.median(),
            "Nota mínima": notas_validas.min(),
            "Nota máxima": notas_validas.max(),
            "Total estudiantes": total,
            "Aprobados": aprob,
            "Reprobados": reprob,
            "% Reprobados": (reprob / total) * 100
        })

    return pd.DataFrame(resultados)


# ================================================
# 3) Widgets
# ================================================
carreras = sorted(fusion["Carrera"].unique())
gestiones = sorted(fusion["Gestión"].unique())
generos = ["Todos"] + sorted(fusion["Género"].dropna().unique())

selector_carrera = widgets.Dropdown(
    options=carreras,
    description="Carrera:",
    layout=widgets.Layout(width="250px")
)

selector_gestion = widgets.Dropdown(
    options=gestiones,
    description="Gestión:",
    layout=widgets.Layout(width="150px")
)

selector_genero = widgets.Dropdown(
    options=generos,
    description="Género:",
    layout=widgets.Layout(width="150px")
)

salida = widgets.Output()


# ================================================
# 4) Función para actualizar gráficos
# ================================================
def actualizar_graficos(change):
    with salida:
        clear_output()

        carrera = selector_carrera.value
        gestion = selector_gestion.value
        genero = selector_genero.value

        df_res = analizar_dificultad_por_carrera(fusion, carrera, gestion, genero)

        if df_res.empty:
            print("No hay datos válidos para esta configuración.")
            return

        df_car = fusion[(fusion["Carrera"] == carrera) & (fusion["Gestión"] == gestion)].copy()
        if genero != "Todos":
            df_car = df_car[df_car["Género"] == genero]

        df_long = df_car.melt(
            id_vars=["Carrera"],
            value_vars=columnas_materias,
            var_name="Materia",
            value_name="Nota"
        )

        df_long = df_long[df_long["Nota"] != -1]
        df_long["Materia"] = df_long["Materia"].str.replace("Nota", "")

        # ================================
        # 1) BOX PLOT (categorical colors)
        # ================================
        fig_box = px.box(
            df_long,
            x="Materia",
            y="Nota",
            color="Materia",      # ← cada materia un color
            title=f"Distribución de notas – {carrera} ({gestion}) – {genero}",
            points="all"
        )
        fig_box.update_layout(yaxis_title="Nota", xaxis_title="Materia")
        fig_box.show()

        # ================================
        # 2) PROMEDIO (gradiente azul)
        # ================================
        fig_prom = px.bar(
            df_res.sort_values("Promedio"),
            x="Materia",
            y="Promedio",
            color="Promedio",               # ← degradado azul
            color_continuous_scale="Blues", # ← escala azul original
            title=f"Promedio de notas – {carrera} ({gestion}) – {genero}",
            text="Promedio"
        )
        fig_prom.update_traces(texttemplate='%{text:.1f}', textposition='outside')
        fig_prom.update_layout(yaxis_title="Promedio", xaxis_title="Materia")
        fig_prom.show()


# ================================================
# 5) Conectar eventos
# ================================================
selector_carrera.observe(actualizar_graficos, names="value")
selector_gestion.observe(actualizar_graficos, names="value")
selector_genero.observe(actualizar_graficos, names="value")

# ================================================
# 6) Mostrar interfaz
# ================================================
display(widgets.HBox([selector_carrera, selector_gestion, selector_genero]), salida)

# Ejecutar primera vez
actualizar_graficos(None)

HBox(children=(Dropdown(description='Carrera:', layout=Layout(width='250px'), options=('Biologia', 'Ciencias Q…

Output()

In [21]:
fusion["Colegio"].head()

0                SAN CALIXTO
1                SAN CALIXTO
2    LIBERTADORES DE AMERICA
3                SAN CALIXTO
4            AMERICAN SCHOOL
Name: Colegio, dtype: object

## **7. Evolución Temporal de la Popularidad de Carreras**

Este gráfico muestra cómo ha evolucionado la cantidad de estudiantes que eligen cada carrera a lo largo del tiempo. Permite analizar tendencias por género y comparar la popularidad relativa de las distintas carreras, destacando cuáles han sido las más demandadas en cada período académico.

In [22]:
import pandas as pd
import plotly.express as px
import ipywidgets as widgets
from IPython.display import display, clear_output

# ==========================================================
# 1) Copiar DataFrame y convertir tipos
# ==========================================================
df = fusion.copy()

df["Carrera"] = df["Carrera"].astype(str)
df["Género"] = df["Género"].astype(str)
df["Periodo"] = df["Periodo"].astype(str)
df["Gestión"] = df["Gestión"].astype(int)
df["Colegio"] = df["Administración del Colegio"].astype(str)

# ==========================================================
# 2) Convertir PERIODO + GESTION a FECHA estimada
# ==========================================================
def periodo_a_fecha(row):
    año = row["Gestión"]
    p = row["Periodo"].strip().upper()

    if p == "PRIMERO":
        return pd.Timestamp(año, 1, 1)
    elif p == "SEGUNDO":
        return pd.Timestamp(año, 7, 1)
    elif p in ["SEGUNDO (PSA)", "SEGUNDO(PSA)"]:
        return pd.Timestamp(año, 10, 1)
    return pd.Timestamp(año, 1, 1)

df["Fecha"] = df.apply(periodo_a_fecha, axis=1)

# ==========================================================
# 3) Crear CHECKBOXES dinámicos en lugar de SelectMultiple
# ==========================================================
def crear_checkboxes(lista, ancho="200px"):
    checks = []
    for item in lista:
        cb = widgets.Checkbox(
            value=True,
            description=str(item),
            indent=False,
            layout=widgets.Layout(width=ancho)
        )
        cb._valor = item
        checks.append(cb)
    return checks

carreras_check = crear_checkboxes(sorted(df["Carrera"].unique()), "260px")
generos_check = crear_checkboxes(sorted(df["Género"].unique()), "160px")
colegios_check = crear_checkboxes(sorted(df["Colegio"].unique()), "320px")

# ==========================================================
# 3.1) CONTENEDORES (Tarjetas visuales)
# ==========================================================
carrera_box = widgets.VBox([
    widgets.HTML("<b>Carrera</b>"),
    widgets.GridBox(
        carreras_check,
        layout=widgets.Layout(grid_template_columns="repeat(2, 260px)", grid_gap="4px 10px")
    )
])

genero_box = widgets.VBox([
    widgets.HTML("<b>Género</b>"),
    widgets.VBox(generos_check)
])

colegio_box = widgets.VBox([
    widgets.HTML("<b>Colegio</b>"),
    widgets.GridBox(
        colegios_check,
        layout=widgets.Layout(grid_template_columns="repeat(2, 320px)", grid_gap="4px 10px")
    )
])

filtros_contenido = widgets.HBox(
    [carrera_box, genero_box, colegio_box],
    layout=widgets.Layout(justify_content="space-around", padding="12px")
)

filtros_card = widgets.VBox(
    [
        widgets.HTML("""
        <div style='font-size:16px; font-weight:bold; margin-bottom:4px;'>
            Filtros de Postulantes
        </div>
        <div style='font-size:12px; color:#555;'>
            Marca o desmarca para actualizar el gráfico automáticamente.
        </div>
        """),
        filtros_contenido
    ],
    layout=widgets.Layout(
        border="1px solid #ccc",
        border_radius="8px",
        padding="10px 15px",
        width="100%"
    )
)

filtros_accordion = widgets.Accordion(children=[filtros_card])
filtros_accordion.set_title(0, "Filtros")
filtros_accordion.selected_index = None  # inicia cerrado

salida = widgets.Output()

# ==========================================================
# 4) Funciones auxiliares
# ==========================================================
def _seleccionados(lista_check):
    return [cb._valor for cb in lista_check if cb.value]

# ==========================================================
# 5) Función para actualizar gráfico
# ==========================================================
def actualizar_grafico(_=None):
    with salida:
        clear_output(wait=True)

        carreras_sel = _seleccionados(carreras_check)
        generos_sel = _seleccionados(generos_check)
        colegios_sel = _seleccionados(colegios_check)

        if not carreras_sel or not generos_sel or not colegios_sel:
            print("Selecciona al menos una opción en todos los filtros.")
            return

        df_filtrado = df[
            df["Carrera"].isin(carreras_sel) &
            df["Género"].isin(generos_sel) &
            df["Colegio"].isin(colegios_sel)
        ].copy()

        if df_filtrado.empty:
            print("No hay datos con los filtros aplicados.")
            return

        # -----------------------------
        # Ordenar carreras de mayor a menor
        # -----------------------------
        ranking = df_filtrado.groupby("Carrera")["C.I."].count().sort_values(ascending=False)
        orden = ranking.index.tolist()

        df_filtrado["Carrera"] = pd.Categorical(df_filtrado["Carrera"], categories=orden, ordered=True)

        # -----------------------------
        # Tendencia temporal
        # -----------------------------
        tendencia = df_filtrado.groupby(["Fecha", "Carrera"], observed=True).size().reset_index(name="Cantidad")

        fig = px.line(
            tendencia,
            x="Fecha",
            y="Cantidad",
            color="Carrera",
            markers=True,
            title="Tendencia Temporal de Carreras (Ordenadas por Preferencia)",
        )

        fig.update_layout(height=600, width=1100, title_x=0.5, hovermode="x unified")
        fig.show()

# ==========================================================
# 6) Conectar eventos (cualquier checkbox actualiza)
# ==========================================================
def _on_change(change):
    if change["name"] == "value":
        actualizar_grafico()

for cb in carreras_check + generos_check + colegios_check:
    cb.observe(_on_change, names="value")

# ==========================================================
# 7) Mostrar UI
# ==========================================================
display(widgets.VBox([filtros_accordion, salida]))

actualizar_grafico()

VBox(children=(Accordion(children=(VBox(children=(HTML(value="\n        <div style='font-size:16px; font-weigh…

In [23]:
import pandas as pd
import plotly.express as px
import ipywidgets as widgets
from IPython.display import display, clear_output

# ==========================================================
# 1) Copiar DataFrame y convertir tipos
# ==========================================================
df = fusion.copy()

df["Carrera"] = df["Carrera"].astype(str)
df["Género"] = df["Género"].astype(str)
df["Periodo"] = df["Periodo"].astype(str)
df["Gestión"] = df["Gestión"].astype(int)
df["Colegio"] = df["Colegio"].astype(str)

# ==========================================================
# 2) Convertir PERIODO + GESTION a FECHA estimada
# ==========================================================
def periodo_a_fecha(row):
    año = row["Gestión"]
    p = row["Periodo"].strip().upper()

    if p == "PRIMERO":
        return pd.Timestamp(año, 1, 1)
    elif p == "SEGUNDO":
        return pd.Timestamp(año, 7, 1)
    elif p in ["SEGUNDO (PSA)", "SEGUNDO(PSA)"]:
        return pd.Timestamp(año, 10, 1)
    else:
        return pd.Timestamp(año, 1, 1)

df["Fecha"] = df.apply(periodo_a_fecha, axis=1)

# ==========================================================
# 3) Construcción de CHECKBOXES DINÁMICOS
# ==========================================================

def crear_checkboxes(lista, ancho="200px"):
    checks = []
    for item in sorted(lista):
        cb = widgets.Checkbox(
            value=True,
            description=str(item),
            indent=False,
            layout=widgets.Layout(width=ancho)
        )
        cb._valor = item
        checks.append(cb)
    return checks

carrera_checks = crear_checkboxes(df["Carrera"].unique(), "250px")
genero_checks = crear_checkboxes(df["Género"].unique(), "180px")
colegio_checks = crear_checkboxes(df["Colegio"].unique(), "280px")

# ==========================================================
# 4) CONTENEDORES ESTILO TARJETA
# ==========================================================

def caja_filtro(titulo, checks, columnas=2):
    return widgets.VBox([
        widgets.HTML(f"<b>{titulo}</b>"),
        widgets.GridBox(
            checks,
            layout=widgets.Layout(
                grid_template_columns=f"repeat({columnas}, auto)",
                grid_gap="4px 10px"
            )
        )
    ])

card_carreras = caja_filtro("Carrera", carrera_checks, columnas=2)
card_generos = caja_filtro("Género", genero_checks, columnas=1)
card_colegios = caja_filtro("Colegio", colegio_checks, columnas=1)

filtros_card = widgets.VBox(
    [
        widgets.HTML("""
        <div style='font-size:16px; font-weight:bold; margin-bottom:4px;'>
            Filtros de Postulantes
        </div>
        <div style='font-size:12px; color:#555;'>
            Marca o desmarca opciones para actualizar la tendencia temporal.
        </div>
        """),
        widgets.HBox([card_carreras, card_generos, card_colegios])
    ],
    layout=widgets.Layout(
        border="1px solid #ccc",
        padding="10px 15px",
        border_radius="8px",
        width="100%"
    )
)

filtros_accordion = widgets.Accordion(children=[filtros_card])
filtros_accordion.set_title(0, "Filtros")
filtros_accordion.selected_index = None  # iniciar cerrado

salida = widgets.Output()

# ==========================================================
# 5) Función para obtener valores seleccionados
# ==========================================================
def valores(checks):
    return [cb._valor for cb in checks if cb.value]

# ==========================================================
# 6) Función para actualizar gráfico
# ==========================================================
def actualizar_grafico(_=None):

    with salida:
        clear_output(wait=True)

        carreras_sel = valores(carrera_checks)
        generos_sel = valores(genero_checks)
        colegios_sel = valores(colegio_checks)

        if not carreras_sel or not generos_sel or not colegios_sel:
            print("Selecciona al menos una opción en cada filtro.")
            return

        df_filtrado = df[
            df["Carrera"].isin(carreras_sel) &
            df["Género"].isin(generos_sel) &
            df["Colegio"].isin(colegios_sel)
        ]

        if df_filtrado.empty:
            print("No hay datos para los filtros seleccionados.")
            return

        # Ranking por carreras
        ranking = df_filtrado.groupby("Carrera")["C.I."].count().sort_values(ascending=False)
        orden_carreras = ranking.index.tolist()

        df_filtrado["Carrera"] = pd.Categorical(
            df_filtrado["Carrera"],
            categories=orden_carreras,
            ordered=True
        )

        # Agrupar
        tendencia = df_filtrado.groupby(["Fecha", "Carrera"], observed=True).size().reset_index(name="Cantidad")

        # Gráfico
        fig = px.line(
            tendencia,
            x="Fecha",
            y="Cantidad",
            color="Carrera",
            markers=True,
            title="Tendencia Temporal de Carreras Escogidas",
        )

        fig.update_layout(
            xaxis_title="Fecha",
            yaxis_title="Cantidad de Estudiantes",
            width=1100,
            height=600,
            hovermode="x unified",
        )

        fig.show()

# ==========================================================
# 7) Conectar eventos
# ==========================================================
def cb_change(change):
    if change["name"] == "value":
        actualizar_grafico()

for cb in carrera_checks + genero_checks + colegio_checks:
    cb.observe(cb_change, names="value")

# ==========================================================
# 8) Mostrar interfaz
# ==========================================================
display(widgets.VBox([filtros_accordion, salida]))

actualizar_grafico()

VBox(children=(Accordion(children=(VBox(children=(HTML(value="\n        <div style='font-size:16px; font-weigh…

## **8. Distribución de Carreras por los 10 Colegios con Mayor Cantidad de Estudiantes**

Este gráfico muestra, para los 10 colegios con más estudiantes, la cantidad de alumnos que eligieron cada carrera. Permite comparar rápidamente cuáles son las carreras más populares en cada colegio y cómo se distribuyen entre ellos. Además, se puede filtrar por género para ver diferencias entre hombres y mujeres.

In [24]:
import pandas as pd
import plotly.express as px
import ipywidgets as widgets
from IPython.display import display, clear_output

# ==========================================================
# 1) Copiar DataFrame y convertir tipos
# ==========================================================
df = fusion.copy()
df["Carrera"] = df["Carrera"].astype(str)
df["Género"] = df["Género"].astype(str)
df["Colegio"] = df["Colegio"].astype(str)

# ==========================================================
# 2) Crear CHECKBOXES — mismo estilo del código anterior
# ==========================================================
generos = sorted(df["Género"].unique())

genero_checkboxes = []
for genero in generos:
    cb = widgets.Checkbox(
        value=True,
        description=str(genero),
        indent=False,
        layout=widgets.Layout(width="160px")
    )
    cb._valor = genero
    genero_checkboxes.append(cb)

genero_box = widgets.VBox([
    widgets.HTML("<b>Género</b>"),
    widgets.VBox(genero_checkboxes)
])

filtros_card = widgets.VBox(
    [
        widgets.HTML("""
        <div style='font-size:16px; font-weight:bold; margin-bottom:4px;'>
            Filtros de Estudiantes
        </div>
        <div style='font-size:12px; color:#555;'>
            Marca o desmarca géneros para actualizar el gráfico.
        </div>
        """),
        genero_box
    ],
    layout=widgets.Layout(
        border="1px solid #ccc",
        padding="10px 15px",
        margin="5px 0 10px 0",
        border_radius="8px",
        width="100%"
    )
)

filtros_accordion = widgets.Accordion(children=[filtros_card])
filtros_accordion.set_title(0, "Filtros de Estudiantes")
filtros_accordion.selected_index = None  # Inicia cerrado

salida = widgets.Output()

# ==========================================================
# Función auxiliar para obtener valores seleccionados
# ==========================================================
def _valores_seleccionados(checks):
    return [cb._valor for cb in checks if cb.value]

# ==========================================================
# 3) Función para actualizar gráfico
# ==========================================================
def actualizar_top10_colegios(_=None):
    with salida:
        clear_output(wait=True)

        generos_sel = _valores_seleccionados(genero_checkboxes)
        if not generos_sel:
            print("Selecciona al menos un género para ver el gráfico.")
            return

        # Filtrar por género
        df_filtrado = df[df["Género"].isin(generos_sel)].copy()
        if df_filtrado.empty:
            print("No hay datos para los filtros seleccionados.")
            return

        # Top 10 colegios con más estudiantes
        top_colegios = (
            df_filtrado.groupby("Colegio")["C.I."]
            .count()
            .sort_values(ascending=False)
            .head(10)
            .index
        )
        df_top_colegios = df_filtrado[df_filtrado["Colegio"].isin(top_colegios)]

        # Contar cantidad de estudiantes por Colegio y Carrera
        conteo = (
            df_top_colegios.groupby(["Colegio", "Carrera"])["C.I."]
            .count()
            .reset_index(name="Cantidad")
        )

        # Ordenar carreras dentro de cada colegio
        category_orders = {
            colegio: conteo[conteo["Colegio"] == colegio]
            .sort_values("Cantidad", ascending=True)["Carrera"]
            .tolist()
            for colegio in conteo["Colegio"].unique()
        }

        # Gráfico
        fig = px.bar(
            conteo,
            x="Cantidad",
            y="Carrera",
            color="Carrera",
            orientation='h',
            facet_row="Colegio",
            title="Carreras Elegidas por los 10 Colegios con Más Estudiantes",
            height=600 + 50 * len(conteo["Colegio"].unique()),
            width=1100,
            text="Cantidad",
            category_orders=category_orders
        )

        fig.for_each_annotation(lambda a: a.update(text=""))
        fig.update_layout(
            title_x=0.5,
            showlegend=False,
            margin=dict(l=150, r=50, t=80, b=50)
        )
        fig.show()

# ==========================================================
# 4) Conectar todos los checkboxes al gráfico
# ==========================================================
def _on_checkbox_change(change):
    if change["name"] == "value":
        actualizar_top10_colegios()

for cb in genero_checkboxes:
    cb.observe(_on_checkbox_change, names="value")

# ==========================================================
# 5) Mostrar interfaz
# ==========================================================
display(widgets.VBox([filtros_accordion, salida]))

# Primera ejecución
actualizar_top10_colegios()

VBox(children=(Accordion(children=(VBox(children=(HTML(value="\n        <div style='font-size:16px; font-weigh…

El código muestra quién aprueba más entre colegios fiscales y privados. Primero renombra la columna “Administración del Colegio” a “Tipo” y se asegura de que la columna “Estado” sea binaria, donde 1 significa que el estudiante aprueba. Luego calcula el porcentaje de aprobación para cada tipo de colegio. Con esos valores genera un gráfico tipo donut que compara visualmente la tasa de aprobación entre colegios fiscales y privados, mostrando los porcentajes dentro del gráfico. Al final, permite ver claramente qué tipo de colegio tiene mayor porcentaje de estudiantes aprobados.

In [25]:
from IPython.display import Markdown
display(Markdown("## 5. ¿Quién Aprueba Más? Fiscal vs Privado"))

# Renombra para simplificar si quieres
df = df.rename(columns={"Administración del Colegio": "Tipo"})

# Asegurar que Estado sea binario (1 = aprueba)
df["Estado"] = df["Estado"].astype(int)

tasa = df.groupby("Tipo")["Estado"].mean().round(4) * 100

fig = px.pie(values=tasa.values, names=tasa.index, hole=0.5,
             color_discrete_map={
                 "Colegio Fiscal": "#E74C3C", 
                 "Colegio Privado": "#27AE60"
             },
             title="Tasa de Aprobación por Tipo de Colegio")

fig.update_traces(textinfo='percent+label', textfont_size=20)
fig.update_layout(height=550, title_x=0.5, font=dict(size=18))
fig.show()

## 5. ¿Quién Aprueba Más? Fiscal vs Privado

Este código calcula y muestra cuáles son los colegios con mayor tasa de aprobación. Primero se hace una copia del dataset y se agrupan los datos por cada colegio, obteniendo cuántos estudiantes aprobaron y cuántos se presentaron en total. Luego se filtran únicamente los colegios con un mínimo de 5 postulantes para asegurar resultados más confiables. Con esa información se calcula la tasa de aprobación de cada colegio en porcentaje. Después se seleccionan los 15 colegios con mejor desempeño y se ordenan desde el de mayor tasa al menor. Finalmente, se genera un gráfico de barras horizontal donde se visualiza claramente el porcentaje de aprobación de cada colegio, junto con el número de aprobados respecto al total de postulantes, permitiendo identificar de manera rápida cuáles instituciones presentan los mejores resultados.

In [26]:
# === CELDA NUEVA: Tasa de aprobación por tipo de colegio y colegio ===
df = fusion.copy()


# Gráfico 2: Top 15 colegios por tasa de aprobación (mínimo 5 postulantes)
aprob_por_colegio = df.groupby("Colegio").agg(
    Aprobados=("Estado", "sum"),
    Total=("Estado", "count")
).query("Total >= 5").assign(Tasa=lambda x: x.Aprobados/x.Total*100)

top_aprob = aprob_por_colegio.sort_values("Tasa", ascending=False).head(15).reset_index()

fig2 = px.bar(top_aprob, x="Tasa", y="Colegio", orientation='h',
              text=top_aprob.apply(lambda row: f"{row.Aprobados}/{row.Total}", axis=1),
              title="Top 15 Colegios con Mayor Tasa de Aprobación (≥5 postulantes)",
              color="Tasa", color_continuous_scale="Viridis")
fig2.update_layout(height=600, yaxis={'categoryorder':'total ascending'})
fig2.show()

Este código crea un treemap interactivo que permite visualizar de manera jerárquica cómo se distribuyen los estudiantes según el tipo de colegio del que provienen, su género, la carrera que eligieron y su resultado final (aprobó o no aprobó). Primero se prepara el dataset, estandarizando los nombres de género y del tipo de colegio, además de convertir la variable Estado en un resultado legible como “Aprobó” o “No Aprobó”. Luego se realiza un conteo de estudiantes para cada combinación de estas categorías, lo cual determina el tamaño de cada bloque dentro del gráfico.

El treemap resultante muestra los datos en niveles: inicia por tipo de colegio, luego se divide por género, después por carrera y finalmente por resultado, permitiendo explorar la información de forma profunda y visualmente atractiva. Cada cuadro representa la cantidad de estudiantes, y los colores diferencian aprobados (verde) de no aprobados (rojo). Además, el gráfico es completamente interactivo: permite hacer zoom, mostrar porcentajes y ver detalles al pasar el cursor. Este recurso facilita entender cómo influyen el origen educativo, el género y la elección de carrera en los resultados académicos de los postulantes.

In [27]:
import plotly.express as px
from IPython.display import display

# === PREPARACIÓN RÁPIDA Y BONITA ===
df = fusion.copy()

# Nombres lindos y claros
df["Género"] = df["Género"].str.replace("MASCULINO", "Hombres").replace("FEMENINO", "Mujeres")
df["Tipo"] = df["Administración del Colegio"].replace({"FISCAL": "Colegio Fiscal", "PRIVADA": "Colegio Privado"})
df["Resultado"] = df["Estado"].map({1: "Aprobó", 0: "No Aprobó"})

# Contar para que los cuadrados tengan el tamaño correcto
conteo = df.groupby(["Tipo", "Género", "Carrera", "Resultado"]).size().reset_index(name="Estudiantes")

# === EL ÁRBOL MÁGICO ===
fig = px.treemap(
    conteo,
    path=["Tipo", "Género", "Carrera", "Resultado"],  # ¡Jerarquía perfecta!
    values="Estudiantes",
    color="Resultado",
    color_discrete_map={"Aprobó": "#27AE60", "No Aprobó": "#E74C3C"},
    title="El Árbol de la Vida Universitaria UMSA<br>"
          "<sup>→ Pasa el mouse sobre cualquier cuadrado • Haz clic para hacer zoom • Cada cuadrado = cantidad de estudiantes</sup>",
    height=750,
    template="plotly_white"
)

# ¡Hacerlo AÚN MÁS bonito!
fig.update_traces(
    textinfo="label+value+percent parent",
    textfont_size=16,
    hovertemplate="<b>%{label}</b><br>Estudiantes: %{value}<br>Porcentaje: %{percentParent:.1%}<extra></extra>"
)

fig.update_layout(
    margin=dict(t=100, l=0, r=0, b=0),
    title_x=0.5,
    font=dict(family="Arial Black", size=18, color="#2c3e50")
)

fig.show()

In [28]:
fusion.to_csv("data/analisis/fusion_1.csv", index=False, encoding="utf-8")
# SOLO SIRVE PARA EL ANALISIS DE DATOS